location = "Canada Central"
resource_group_name = "cdscracollab-innovation-rg"
appservice_plan_id = "alphaPlan"
appservice_name = "claim-tax-benefits-app"
docker_image_name = "claimtaxbenefits.azurecr.io/cra-claim-tax-benefits:latest"
appservice_port = "3005"
appservice_log_retention_days = "30"