name: Test, build, deploy
on: push
jobs:
  test:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    name: Run tests
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: npm install
      - name: Run jest unit tests
        run: npm test
      - name: Run JS linter
        run: npm run lint
      - name: Run Cypress end-to-end
        uses: cypress-io/github-action@v1
        with:
          # we have already installed all dependencies above
          install: false
          start: npm run start:cypress
